# Generated by Django 2.1.1 on 2018-11-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='Atividade',
            new_name='atividade',
        ),
    ]
