# Generated by Django 2.1.3 on 2018-11-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20181106_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
