# Generated by Django 2.1.3 on 2018-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_auto_20181108_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
