# Generated by Django 2.1.1 on 2018-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_auto_20181105_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano/Módulo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=200, verbose_name='Código'),
        ),
    ]
