# Generated by Django 2.1.1 on 2018-11-05 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0003_auto_20181105_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=200, verbose_name='Nome da disciplina')),
                ('Atividade', models.CharField(max_length=200, verbose_name='Nome da atividade')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de Cadastro')),
                ('data_entrega', models.DateTimeField(verbose_name='Data de Entrega')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma'),
        ),
    ]
