# Generated by Django 2.1.1 on 2018-11-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0005_auto_20181105_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('data_comentario', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='criador',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='adm',
            new_name='aluno',
        ),
        migrations.AddField(
            model_name='comentario',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Atividade'),
        ),
    ]
