# Generated by Django 2.1.1 on 2018-11-05 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0007_alunoemturma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunoemturma',
            options={'verbose_name_plural': 'Alunos em Turmas'},
        ),
        migrations.AlterUniqueTogether(
            name='alunoemturma',
            unique_together={('aluno', 'turma')},
        ),
    ]
