# Generated by Django 2.1.1 on 2018-11-05 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0008_auto_20181105_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Atividade')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='prioridade',
            unique_together={('aluno', 'atividade')},
        ),
    ]
