# Generated by Django 2.1.1 on 2018-11-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_auto_20181105_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='prioridade',
        ),
        migrations.AlterUniqueTogether(
            name='prioridade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prioridade',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='prioridade',
            name='atividade',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='Prioridade',
        ),
    ]
