# Generated by Django 2.1.1 on 2018-11-06 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0011_auto_20181105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
