# Generated by Django 2.1.3 on 2018-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0012_turma_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Código'),
        ),
    ]
